security:
  basic.enabled: true
  sessions: stateless # Session creation policy (always, never, if_required, stateless).
  user:
    name: MetraViewUser # Default user name.
    password: EcbExcellence00123 # Password for the default user name. A random password is logged on startup by default.
    role: USER # Granted roles for the default user name.
